#!/bin/bash

# Orion RWA Lending - Bot Key Setup Script
# This script helps generate and configure bot keys

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Orion RWA Lending - Bot Key Setup                    ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if stellar CLI is installed
if ! command -v stellar &> /dev/null; then
    echo -e "${RED}❌ Stellar CLI not found${NC}"
    echo -e "   Install from: https://developers.stellar.org/docs/tools/developer-tools"
    exit 1
fi

echo -e "${GREEN}✓${NC} Stellar CLI found"
echo ""

# Function to generate bot key
generate_bot_key() {
    local BOT_NAME=$1
    local KEY_NAME=$2

    echo -e "${YELLOW}Checking key for ${BOT_NAME}...${NC}" >&2

    # Check if key exists
    if stellar keys address "$KEY_NAME" > /dev/null 2>&1; then
        echo -e "${GREEN}✓ Key '${KEY_NAME}' already exists.${NC}" >&2
    else
        echo -e "${YELLOW}Generating key for ${BOT_NAME}...${NC}" >&2
        # Generate and fund the account
        stellar keys generate "$KEY_NAME" --network testnet --fund >&2
    fi

    # Get the public and secret keys
    local PUBLIC_KEY=$(stellar keys address "$KEY_NAME")
    local SECRET_KEY=$(stellar keys show "$KEY_NAME")

    echo -e "${GREEN}✓ Configuration for ${BOT_NAME}:${NC}" >&2
    echo -e "  Public:  ${BLUE}${PUBLIC_KEY}${NC}" >&2
    echo -e "  Secret:  ${PURPLE}(hidden)${NC}" >&2
    echo "" >&2

    # Return the secret key for env file
    echo "$SECRET_KEY"
}

echo -e "${BLUE}This script will generate 3 bot accounts on Stellar testnet:${NC}"
echo -e "  1. Oracle Price Bot"
echo -e "  2. Auto-Repay Bot"
echo -e "  3. Liquidation Bot"
echo ""
echo -e "${YELLOW}Each account will be funded with testnet XLM${NC}"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${RED}Aborted${NC}"
    exit 1
fi

echo ""

# Generate keys
ORACLE_SECRET=$(generate_bot_key "Oracle Price Bot" "oracle-bot-testnet")
AUTO_REPAY_SECRET=$(generate_bot_key "Auto-Repay Bot" "auto-repay-bot-testnet")
LIQUIDATION_SECRET=$(generate_bot_key "Liquidation Bot" "liquidation-bot-testnet")

# Create .env files
echo -e "${YELLOW}Creating .env files...${NC}"

# Oracle Bot .env
cat > bots/oracle-price-bot/.env << EOF
# Auto-generated by setup-bot-keys.sh
STELLAR_NETWORK=testnet
STELLAR_RPC_URL=https://soroban-testnet.stellar.org
STELLAR_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
BOT_SECRET_KEY=${ORACLE_SECRET}
ORACLE_CONTRACT_ID=CD5XYT6WXOB567JC3QZGJ7RWHWP4N3C4GJ5LX75WDWUGL7NPXFJJC6AZ
STRWA_TOKEN_ADDRESS=CCCTL6UHRPOODYKYOXAW6Y3NKOFPFKB7QIYRRYGEANM2KHYYYAT4PJUS
PORT=3000
EOF
echo -e "${GREEN}✓ Created bots/oracle-price-bot/.env${NC}"

# Auto-Repay Bot .env
cat > bots/auto-repay-bot/.env << EOF
# Auto-generated by setup-bot-keys.sh
STELLAR_NETWORK=testnet
STELLAR_RPC_URL=https://soroban-testnet.stellar.org
STELLAR_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
BOT_SECRET_KEY=${AUTO_REPAY_SECRET}
VAULT_CONTRACT_ID=CB3I43AX6VBYTHLVGXK3TVM5RZXLTSHT5RIHOTK2BHORNQY3RF3QH2TT
LENDING_POOL_CONTRACT_ID=CBJM554JCHWRFG7QFBKMPAPOO4DBJPLKHSH2T7U4FRLCPDS36U44WT5Y
PORT=3001
CHECK_INTERVAL=300000
MIN_REPAYMENT_AMOUNT=1000000
LOG_LEVEL=info
EOF
echo -e "${GREEN}✓ Created bots/auto-repay-bot/.env${NC}"

# Liquidation Bot .env
cat > bots/liquidation-bot/.env << EOF
# Auto-generated by setup-bot-keys.sh
STELLAR_NETWORK=testnet
STELLAR_RPC_URL=https://soroban-testnet.stellar.org
STELLAR_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
BOT_SECRET_KEY=${LIQUIDATION_SECRET}
LENDING_POOL_CONTRACT_ID=CBJM554JCHWRFG7QFBKMPAPOO4DBJPLKHSH2T7U4FRLCPDS36U44WT5Y
ORACLE_CONTRACT_ID=CD5XYT6WXOB567JC3QZGJ7RWHWP4N3C4GJ5LX75WDWUGL7NPXFJJC6AZ
STRWA_TOKEN_ADDRESS=CCCTL6UHRPOODYKYOXAW6Y3NKOFPFKB7QIYRRYGEANM2KHYYYAT4PJUS
PORT=3002
CHECK_INTERVAL=300000
WARNING_THRESHOLD_1=150
WARNING_THRESHOLD_2=120
WARNING_THRESHOLD_3=110
LIQUIDATION_THRESHOLD=110
LOG_LEVEL=info
EOF
echo -e "${GREEN}✓ Created bots/liquidation-bot/.env${NC}"

# Orchestrator .env
cat > bots/orchestrator/.env << EOF
# Auto-generated by setup-bot-keys.sh
STELLAR_NETWORK=testnet
STELLAR_RPC_URL=https://soroban-testnet.stellar.org
STELLAR_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
ORACLE_BOT_SECRET_KEY=${ORACLE_SECRET}
AUTO_REPAY_BOT_SECRET_KEY=${AUTO_REPAY_SECRET}
LIQUIDATION_BOT_SECRET_KEY=${LIQUIDATION_SECRET}
USDC_CONTRACT_ID=CAXHQJ6IHN2TPAJ4NEOXJJLRRAO74BEAWA3RXHD6NSOWRBQCTVZA3ZGS
RWA_TOKEN_CONTRACT_ID=CCHUQ75NY5CFWIXG42RJRZQDMZ2HOAERS4RSX4EL6EEOUE6OMOFLBFVV
STRWA_TOKEN_CONTRACT_ID=CCCTL6UHRPOODYKYOXAW6Y3NKOFPFKB7QIYRRYGEANM2KHYYYAT4PJUS
VAULT_CONTRACT_ID=CB3I43AX6VBYTHLVGXK3TVM5RZXLTSHT5RIHOTK2BHORNQY3RF3QH2TT
ORACLE_CONTRACT_ID=CD5XYT6WXOB567JC3QZGJ7RWHWP4N3C4GJ5LX75WDWUGL7NPXFJJC6AZ
LENDING_POOL_CONTRACT_ID=CBJM554JCHWRFG7QFBKMPAPOO4DBJPLKHSH2T7U4FRLCPDS36U44WT5Y
METRICS_PORT=9090
LOG_LEVEL=info
EOF
echo -e "${GREEN}✓ Created bots/orchestrator/.env${NC}"

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  Bot keys generated and configured successfully!       ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo -e "  1. Review .env files in each bot directory"
echo -e "  2. Start bots: ${YELLOW}./start-bots.sh${NC}"
echo -e "  3. Check status: ${YELLOW}./status-bots.sh${NC}"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT:${NC}"
echo -e "  These are testnet accounts. Do NOT use these keys on mainnet!"
echo -e "  Keep your secret keys secure and never commit them to git."
echo ""
